apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:  
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
       - name: persistent-storage
         persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: pbadhe34/my-apps:mysql-users
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "MyRootPass123" 
         - name: MYSQL_DATABASE
           value: userservice
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: persistent-storage
            mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: user-app
    spec:       
      containers:
      - name: user-app
        image: pbadhe34/my-apps:user-app
        ports:
        - containerPort: 8090
        env:
          - name: mysql
            value: "mysql"        
---
apiVersion: v1
kind: Service
metadata:
  name: user-app
spec:
  type: NodePort
  ports:
  - port: 8090
  selector:
    app: user-app