FROM tomcat:8.0-jre8 

RUN apt-get update && apt-get -y upgrade

WORKDIR /usr/local/tomcat

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY server.xml /usr/local/tomcat/conf/server.xml
COPY Rest-JPA-App.war /usr/local/tomcat/webapps/JPA-REST-App.war


EXPOSE 8090