version: '3'
services:
  web:
    image: pbadhe34/apps:spring-rest-mysql
    ports:
     - "8090:8090"
  mysql-server:
   image: mysql:8.0.24
   environment:
      MYSQL_ROOT_PASSWORD: "MyRootPass123"
      MYSQL_DATABASE: mydb
      MYSQL_USER: app-user
      MYSQL_PASSWORD: "MyRootPass123"
   volumes:
        - /c/mysqldata:/var/lib/mysql/data